#!/bin/bash

# Crear directorios necesarios
mkdir -p static/fotos static/css static/img temp .well-known

# Crear archivo de verificación para CapRover
echo "OK" > .well-known/captain-identifier

# Verificar si existe products.csv, si no, crearlo
if [ ! -f products.csv ]; then
    echo "sku,titulo,descripcion,descripcion_larga,costo_transporte,descartador,imagen_url,categorias" > products.csv
    echo "Archivo products.csv creado"
fi

# Verificar si existe materiales.csv, si no, crearlo
if [ ! -f materiales.csv ]; then
    echo "material,descripcion,categoria,imagen_url" > materiales.csv
    echo "Archivo materiales.csv creado"
fi

# Crear placeholder para imágenes no encontradas
if [ ! -f static/img/placeholder.png ]; then
    echo "Creando imagen placeholder..."
    # Crear un archivo placeholder si no existe
    echo "iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAIAAADTED8xAAAACXBIWXMAAAsTAAALEwEAmpwYAAAGAGlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDAgNzkuMTYwNDUxLCAyMDE3LzA1LzA2LTAxOjA4OjIxICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHVybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV2ZW50IyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOCAoTWFjaW50b3NoKSIgeG1wOkNyZWF0ZURhdGU9IjIwMjMtMTItMjBUMTI6MDA6MDAtMDM6MDAiIHhtcDpNb2RpZnlEYXRlPSIyMDIzLTEyLTIwVDEyOjAxOjEzLTAzOjAwIiB4bXA6TWV0YWRhdGFEYXRlPSIyMDIzLTEyLTIwVDEyOjAxOjEzLTAzOjAwIiBkYzpmb3JtYXQ9ImltYWdlL3BuZyIgcGhvdG9zaG9wOkNvbG9yTW9kZT0iMyIgcGhvdG9zaG9wOklDQ1Byb2ZpbGU9InNSR0IgSUVDNjE5NjYtMi4xIiB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOmFiZDg5YTYtYWQ4MC00Y2UwLTkzNjktZThjODZkZDY1OWZkIiB4bXBNTTpEb2N1bWVudElEPSJhZG9iZTpkb2NpZDpwaG90b3Nob3A6MjI3NGJlNTQtMWE3Yi0yZTQ0LTkwNzQtNTAzM2FkYTg4YzEzIiB4bXBNTTpPcmlnaW5hbERvY3VtZW50SUQ9InhtcC5kaWQ6YTgxODdjNTYtMjZkZS00NmFiLTkzYzYtN2YwZmM3N2Y1OWE2Ij4gPHhtcE1NOkhpc3Rvcnk+IDxyZGY6U2VxPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0iY3JlYXRlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDphODE4N2M1Ni0yNmRlLTQ2YWItOTNjNi03ZjBmYzc3ZjU5YTYiIHN0RXZ0OndoZW49IjIwMjMtMTItMjBUMTI6MDA6MDAtMDM6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCBDQyAyMDE4IChNYWNpbnRvc2gpIi8+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJzYXZlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDphYmQ4OWE2LWFkODAtNGNlMC05MzY5LWU4YzgyZGQ2NTlmZCIgc3RFdnQ6d2hlbj0iMjAyMy0xMi0yMFQxMjowMToxMy0wMzowMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIENDIDIwMTggKE1hY2ludG9zaCkiIHN0RXZ0OmNoYW5nZWQ9Ii8iLz4gPC9yZGY6U2VxPiA8L3htcE1NOkhpc3Rvcnk+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8+HBkZ3QAAAHRJREFUeJztwTEBAAAAwqD1T20MH6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL4G+ZsAAf6mQlMAAAAASUVORK5CYII=" | base64 -d > static/img/placeholder.png
fi

# Asegurar permisos correctos
chmod -R 755 static templates || true
chmod -R 777 static/fotos temp || true
chmod 666 *.csv || true

echo "Configuración completada. Se ejecutará gunicorn para iniciar la aplicación en producción." 